#pragma once

#include "Main.h"

#define MONSTER_GENDERLESS 0xFF
#define MONSTER_FEMALE 0xFE
#define MONSTER_MALE 0x00
#define PERCENT_FEMALE(percent) min(254, ((percent * 255) / 100))

const struct BaseStats gBaseStats[] =			//////setting up basestats for all monsters in the game systematically by array of species
{
	[MONSTER_NULL] = {0},
	[MONSTER_WOLF] =
	{
		.baseHP = 50,
		.baseAttack = 70,
		.baseDefense = 65,
		.baseSpeed = 55,
		.basePsi = 45,
		.baseResolve = 40,
		.element1 = ELEMENT_NONE,
		.element2 = ELEMENT_NULL,
		.catchrate = 190,
		.expYield = 48,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_EARTHWOLF] =
	{
		.baseHP = 120,
		.baseAttack = 100,
		.baseDefense = 110,
		.baseSpeed = 65,
		.basePsi = 65,
		.baseResolve = 65,
		.element1 = ELEMENT_EARTH,
		.element2 = ELEMENT_NULL,
		.catchrate = 150,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_AIRWOLF] =
	{
		.baseHP = 65,
		.baseAttack = 100,
		.baseDefense = 65,
		.baseSpeed = 120,
		.basePsi = 110,
		.baseResolve = 65,
		.element1 = ELEMENT_AIR,
		.element2 = ELEMENT_NULL,
		.catchrate = 150,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_FIREWOLF] =
	{
		.baseHP = 65,
		.baseAttack = 120,
		.baseDefense = 65,
		.baseSpeed = 100,
		.basePsi = 110,
		.baseResolve = 65,
		.element1 = ELEMENT_FIRE,
		.element2 = ELEMENT_NULL,
		.catchrate = 150,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_WATERWOLF] =
	{
		.baseHP = 110,
		.baseAttack = 65,
		.baseDefense = 65,
		.baseSpeed = 65,
		.basePsi = 100,
		.baseResolve = 120,
		.element1 = ELEMENT_WATER,
		.element2 = ELEMENT_NULL,
		.catchrate = 150,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_ELECTRICWOLF] =
	{
		.baseHP = 65,
		.baseAttack = 65,
		.baseDefense = 65,
		.baseSpeed = 120,
		.basePsi = 110,
		.baseResolve = 100,
		.element1 = ELEMENT_ELECTRIC,
		.element2 = ELEMENT_NULL,
		.catchrate = 150,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_METALWOLF] =
	{
		.baseHP = 100,
		.baseAttack = 65,
		.baseDefense = 120,
		.baseSpeed = 65,
		.basePsi = 65,
		.baseResolve = 110,
		.element1 = ELEMENT_METAL,
		.element2 = ELEMENT_NULL,
		.catchrate = 150,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_SOULWOLF] =
	{
		.baseHP = 65,
		.baseAttack = 65,
		.baseDefense = 65,
		.baseSpeed = 100,
		.basePsi = 120,
		.baseResolve = 110,
		.element1 = ELEMENT_SOUL,
		.element2 = ELEMENT_NULL,
		.catchrate = 150,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_LIFEWOLF] =
	{
		.baseHP = 65,
		.baseAttack = 100,
		.baseDefense = 120,
		.baseSpeed = 110,
		.basePsi = 65,
		.baseResolve = 65,
		.element1 = ELEMENT_LIFE,
		.element2 = ELEMENT_NULL,
		.catchrate = 150,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_DEATHWOLF] =
	{
		.baseHP = 60,
		.baseAttack = 115,
		.baseDefense = 60,
		.baseSpeed = 115,
		.basePsi = 115,
		.baseResolve = 60,
		.element1 = ELEMENT_DEATH,
		.element2 = ELEMENT_NULL,
		.catchrate = 150,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
};