#pragma once

#include "Main.h"

#define MONSTER_GENDERLESS 0xFF
#define MONSTER_FEMALE 0xFE
#define MONSTER_MALE 0x00
#define PERCENT_FEMALE(percent) min(254, ((percent * 255) / 100))

const struct BaseStats gBaseStats[] =			//////setting up basestats for all monsters in the game systematically by array of species
{
	[MONSTER_NULL] = {0},
	[MONSTER_WOLF] =
	{
		.baseHP = 50,
		.baseAttack = 70,
		.baseDefense = 65,
		.baseSpeed = 55,
		.basePsi = 45,
		.baseResolve = 40,
		.element1 = ELEMENT_NONE,
		.element2 = ELEMENT_NULL,
		.catchrate = 150,
		.upgradeType = UPGRADE_TYPE_USEITEM,
		.upgradeLvl = 0,
		.expYield = 48,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_EARTHWOLF] =
	{
		.baseHP = 120,
		.baseAttack = 100,
		.baseDefense = 110,
		.baseSpeed = 65,
		.basePsi = 65,
		.baseResolve = 65,
		.element1 = ELEMENT_EARTH,
		.element2 = ELEMENT_NULL,
		.catchrate = 100,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_AIRWOLF] =
	{
		.baseHP = 65,
		.baseAttack = 100,
		.baseDefense = 65,
		.baseSpeed = 120,
		.basePsi = 110,
		.baseResolve = 65,
		.element1 = ELEMENT_AIR,
		.element2 = ELEMENT_NULL,
		.catchrate = 100,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_FIREWOLF] =
	{
		.baseHP = 65,
		.baseAttack = 120,
		.baseDefense = 65,
		.baseSpeed = 100,
		.basePsi = 110,
		.baseResolve = 65,
		.element1 = ELEMENT_FIRE,
		.element2 = ELEMENT_NULL,
		.catchrate = 100,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_WATERWOLF] =
	{
		.baseHP = 110,
		.baseAttack = 65,
		.baseDefense = 65,
		.baseSpeed = 65,
		.basePsi = 100,
		.baseResolve = 120,
		.element1 = ELEMENT_WATER,
		.element2 = ELEMENT_NULL,
		.catchrate = 100,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_ELECTRICWOLF] =
	{
		.baseHP = 65,
		.baseAttack = 65,
		.baseDefense = 65,
		.baseSpeed = 120,
		.basePsi = 110,
		.baseResolve = 100,
		.element1 = ELEMENT_ELECTRIC,
		.element2 = ELEMENT_NULL,
		.catchrate = 100,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_METALWOLF] =
	{
		.baseHP = 100,
		.baseAttack = 65,
		.baseDefense = 120,
		.baseSpeed = 65,
		.basePsi = 65,
		.baseResolve = 110,
		.element1 = ELEMENT_METAL,
		.element2 = ELEMENT_NULL,
		.catchrate = 100,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_SOULWOLF] =
	{
		.baseHP = 65,
		.baseAttack = 65,
		.baseDefense = 65,
		.baseSpeed = 100,
		.basePsi = 120,
		.baseResolve = 110,
		.element1 = ELEMENT_SOUL,
		.element2 = ELEMENT_NULL,
		.catchrate = 100,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_LIFEWOLF] =
	{
		.baseHP = 65,
		.baseAttack = 100,
		.baseDefense = 120,
		.baseSpeed = 110,
		.basePsi = 65,
		.baseResolve = 65,
		.element1 = ELEMENT_LIFE,
		.element2 = ELEMENT_NULL,
		.catchrate = 100,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	[MONSTER_DEATHWOLF] =
	{
		.baseHP = 60,
		.baseAttack = 115,
		.baseDefense = 60,
		.baseSpeed = 115,
		.basePsi = 115,
		.baseResolve = 60,
		.element1 = ELEMENT_DEATH,
		.element2 = ELEMENT_NULL,
		.catchrate = 100,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_RUFF_HOUSE, ABILITY_NONE, ABILITY_RUFF_HOUSE}
	},
	/*[MONSTER_NEWUT] =		//TOADD:
	{
		.baseHP = 46,
		.baseAttack = 43,
		.baseDefense = 52,
		.baseSpeed = 49,
		.basePsi = 71,
		.baseResolve = 56,
		.element1 = ELEMENT_NONE,
		.element2 = ELEMENT_NULL,
		.catchrate = 170,
		.upgradeType = UPGRADE_TYPE_LVLUP,
		.upgradeLvl = 19,
		.expYield = 32,
		.trainingYieldPsi = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_SLIMY_SKIN, ABILITY_NONE, ABILITY_SWIFT_SWIMMER}
	},
	[MONSTER_NEWUND] =
	{
		.baseHP = 73,
		.baseAttack = 77,
		.baseDefense = 86,
		.baseSpeed = 83,
		.basePsi = 103,
		.baseResolve = 85,
		.element1 = ELEMENT_NONE,
		.element2 = ELEMENT_WATER,
		.catchrate = 140,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 56,
		.trainingYieldPsi = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_SLIMY_SKIN, ABILITY_NONE, ABILITY_SWIFT_SWIMMER}
	},
	[MONSTER_CLAYNEE] =
	{
		.baseHP = 56,
		.baseAttack = 67,
		.baseDefense = 43,
		.baseSpeed = 45,
		.basePsi = 34,
		.baseResolve = 65,
		.element1 = ELEMENT_EARTH,
		.element2 = ELEMENT_NULL,
		.catchrate = 170,
		.upgradeType = UPGRADE_TYPE_LVLUP,
		.upgradeLvl = 22,
		.expYield = 32,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_DRY_BODY, ABILITY_NONE, ABILITY_HYDROPHILIC}
	},
	[MONSTER_MUDDEN] =
	{
		.baseHP = 87,
		.baseAttack = 102,
		.baseDefense = 74,
		.baseSpeed = 78,
		.basePsi = 68,
		.baseResolve = 96,
		.element1 = ELEMENT_EARTH,
		.element2 = ELEMENT_WATER,
		.catchrate = 125,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_DRY_BODY, ABILITY_NONE, ABILITY_HYDROPHILIC}
	},
	[MONSTER_STRATLIA] =
	{
		.baseHP = 61,
		.baseAttack = 71,
		.baseDefense = 51,
		.baseSpeed = 37,
		.basePsi = 36,
		.baseResolve = 56,
		.element1 = ELEMENT_NONE,
		.element2 = ELEMENT_EARTH,
		.catchrate = 160,
		.upgradeType = UPGRADE_TYPE_LVLUP,
		.upgradeLvl = 24,
		.expYield = 32,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_ROCK_SOLID, ABILITY_NONE, ABILITY_NONE}
	},
	[MONSTER_SEDIMEAN] =
	{
		.baseHP = 92,
		.baseAttack = 121,
		.baseDefense = 82,
		.baseSpeed = 67,
		.basePsi = 54,
		.baseResolve = 93,
		.element1 = ELEMENT_EARTH,
		.element2 = ELEMENT_NULL,
		.catchrate = 115,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 72,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_ROCK_SOLID, ABILITY_NONE, ABILITY_NONE}
	},
	[MONSTER_HAWKLIN] =
	{
		.baseHP = 36,
		.baseAttack = 56,
		.baseDefense = 39,
		.baseSpeed = 41,
		.basePsi = 26,
		.baseResolve = 22,
		.element1 = ELEMENT_NONE,
		.element2 = ELEMENT_NULL,
		.catchrate = 180,
		.upgradeType = UPGRADE_TYPE_LVLUP,
		.upgradeLvl = 15,
		.expYield = 24,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_KEEN_EYE, ABILITY_WATCHFUL, ABILITY_INTIMIDATE}
	},
	[MONSTER_SQUAKEEN] =
	{
		.baseHP = 56,
		.baseAttack = 75,
		.baseDefense = 62,
		.baseSpeed = 63,
		.basePsi = 47,
		.baseResolve = 41,
		.element1 = ELEMENT_NONE,
		.element2 = ELEMENT_AIR,
		.catchrate = 150,
		.upgradeType = UPGRADE_TYPE_LVLUP,
		.upgradeLvl = 24,
		.expYield = 48,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_KEEN_EYE, ABILITY_WATCHFUL, ABILITY_INTIMIDATE}
	},
	[MONSTER_HOWLDREGE] =
	{
		.baseHP = 81,
		.baseAttack = 111,
		.baseDefense = 83,
		.baseSpeed = 91,
		.basePsi = 76,
		.baseResolve = 65,
		.element1 = ELEMENT_NONE,
		.element2 = ELEMENT_AIR,
		.catchrate = 110,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_KEEN_EYE, ABILITY_WATCHFUL, ABILITY_INTIMIDATE}
	},
	[MONSTER_LILYTAD] =
	{
		.baseHP = 27,
		.baseAttack = 38,
		.baseDefense = 23,
		.baseSpeed = 41,
		.basePsi = 43,
		.baseResolve = 37,
		.element1 = ELEMENT_WATER,
		.element2 = ELEMENT_NULL,
		.catchrate = 180,
		.upgradeType = UPGRADE_TYPE_LVLUP,
		.upgradeLvl = 16,
		.expYield = 24,
		.trainingYieldPsi = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_PHOTOSYNTHESIS, ABILITY_NONE, ABILITY_SOLAR_POWER}
	},
	[MONSTER_LILYBUD] =
	{
		.baseHP = 44,
		.baseAttack = 49,
		.baseDefense = 43,
		.baseSpeed = 66,
		.basePsi = 77,
		.baseResolve = 71,
		.element1 = ELEMENT_WATER,
		.element2 = ELEMENT_LIFE,
		.catchrate = 160,
		.upgradeType = UPGRADE_TYPE_LVLUP,
		.upgradeLvl = 26,
		.expYield = 32,
		.trainingYieldPsi = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_PHOTOSYNTHESIS, ABILITY_NONE, ABILITY_SOLAR_POWER}
	},
	[MONSTER_LILYBLOOM] =
	{
		.baseHP = 76,
		.baseAttack = 69,
		.baseDefense = 71,
		.baseSpeed = 82,
		.basePsi = 109,
		.baseResolve = 93,
		.element1 = ELEMENT_WATER,
		.element2 = ELEMENT_NULL,
		.catchrate = 130,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 48,
		.trainingYieldPsi = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_PHOTOSYNTHESIS, ABILITY_NONE, ABILITY_SOLAR_POWER}
	},
	[MONSTER_PSIMATE] =
	{
		.baseHP = 65,
		.baseAttack = 104,
		.baseDefense = 72,
		.baseSpeed = 89,
		.basePsi = 107,
		.baseResolve = 76,
		.element1 = ELEMENT_NONE,
		.element2 = ELEMENT_NULL,
		.catchrate = 150,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 36,
		.trainingYieldPsi = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_FORESIGHT, ABILITY_WATCHFUL, ABILITY_NONE}
	},
	[MONSTER_BRAMBLING] =
	{
		.baseHP = 40,
		.baseAttack = 55,
		.baseDefense = 71,
		.baseSpeed = 35,
		.basePsi = 30,
		.baseResolve = 62,
		.element1 = ELEMENT_LIFE,
		.element2 = ELEMENT_NULL,
		.catchrate = 140,
		.upgradeType = UPGRADE_TYPE_LVLUP,
		.upgradeLvl = 23,
		.expYield = 32,
		.trainingYieldDefense = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_THORNS, ABILITY_NONE, ABILITY_NONE}
	},
	[MONSTER_TOXITHORN] =
	{
		.baseHP = 80,
		.baseAttack = 87,
		.baseDefense = 121,
		.baseSpeed = 66,
		.basePsi = 55,
		.baseResolve = 104,
		.element1 = ELEMENT_LIFE,
		.element2 = ELEMENT_DEATH,
		.catchrate = 105,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 64,
		.trainingYieldDefense = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_THORNS, ABILITY_NONE, ABILITY_NONE}
	},
	[MONSTER_INFANTREE] =
	{
		.baseHP = 50,
		.baseAttack = 58,
		.baseDefense = 45,
		.baseSpeed = 33,
		.basePsi = 20,
		.baseResolve = 19,
		.element1 = ELEMENT_LIFE,
		.element2 = ELEMENT_NULL,
		.catchrate = 175,
		.upgradeType = UPGRADE_TYPE_LVLUP,
		.upgradeLvl = 12,
		.expYield = 16,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_BRAVERY, ABILITY_NONE, ABILITY_NONE}
	},
	[MONSTER_GERMAKNIGHT] =
	{
		.baseHP = 72,
		.baseAttack = 79,
		.baseDefense = 67,
		.baseSpeed = 54,
		.basePsi = 39,
		.baseResolve = 39,
		.element1 = ELEMENT_LIFE,
		.element2 = ELEMENT_NULL,
		.catchrate = 155,
		.upgradeType = UPGRADE_TYPE_LVLUP,
		.upgradeLvl = 21,
		.expYield = 28,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_BRAVERY, ABILITY_NONE, ABILITY_NONE}
	},
	[MONSTER_STALKKING] =
	{
		.baseHP = 98,
		.baseAttack = 117,
		.baseDefense = 88,
		.baseSpeed = 76,
		.basePsi = 57,
		.baseResolve = 58,
		.element1 = ELEMENT_LIFE,
		.element2 = ELEMENT_NULL,
		.catchrate = 110,
		.upgradeType = UPGRADE_TYPE_MAX,
		.upgradeLvl = 0,
		.expYield = 64,
		.trainingYieldAttack = 1,
		.genderRatio = PERCENT_FEMALE(22.5),
		.eggHatch = 20,
		.friendship = 70,
		.growthRate = GROWTH_RATE_NORMAL,
		.eggGroup1 = 1,
		.eggGroup2 = 1,
		.abilities = {ABILITY_BRAVERY, ABILITY_NONE, ABILITY_NONE}
	},*/
};