#pragma once


///////////////////////////////MISC////////////////////////////////////

#define GROWTH_RATE_VERY_FAST 0
#define GROWTH_RATE_FAST 1
#define GROWTH_RATE_NORMAL 2
#define GROWTH_RATE_SLOW 3
#define GROWTH_RATE_VERY_SLOW 4
#define GROWTH_RATE_LEGENDARY 5

///////////////////////////////MISC////////////////////////////////////

//////////////////////////////ITEMS////////////////////////////////////

#define ITEMTYPE_EQUIP 0
#define ITEMTYPE_USE 1
#define ITEMTYPE_VALUE 2
#define ITEMTYPE_ADVENTURE 3

#define INV_EQUIP_ITEM_0 0
#define INV_EQUIP_ITEM_1 1
#define INV_EQUIP_ITEM_2 2
#define INV_EQUIP_ITEM_3 3
#define INV_EQUIP_ITEM_4 4
#define INV_EQUIP_ITEM_5 5
#define INV_EQUIP_ITEM_6 6
#define INV_EQUIP_ITEM_7 7
#define INV_EQUIP_ITEM_8 8
#define INV_EQUIP_ITEM_9 9
#define INV_EQUIP_ITEM_10 10
#define INV_EQUIP_ITEM_11 11
#define INV_EQUIP_ITEM_12 12
#define INV_EQUIP_ITEM_13 13
#define INV_EQUIP_ITEM_14 14
#define INV_EQUIP_ITEM_15 15
#define INV_EQUIP_ITEM_16 16
#define INV_EQUIP_ITEM_17 17
#define INV_EQUIP_ITEM_18 18
#define INV_EQUIP_ITEM_19 19
#define INV_EQUIP_ITEM_20 20
#define INV_EQUIP_ITEM_21 21
#define INV_EQUIP_ITEM_22 22
#define INV_EQUIP_ITEM_23 23
#define INV_EQUIP_ITEM_24 24

#define NUM_EQUIP_ITEMS 25

#define ITEM_EQUIP_EFFECT_NULL 0
#define ITEM_EQUIP_EFFECT_NONE 1
#define ITEM_EQUIP_EFFECT_ELEMENT_BOOST 2
#define ITEM_EQUIP_EFFECT_HEAL_BELOW_ONETHIRD 3
#define ITEM_EQUIP_EFFECT_HEAL_BELOW_ONEEIGHTH 4
#define ITEM_EQUIP_EFFECT_HEAL_IMMEDIATELY 5
#define ITEM_EQUIP_EFFECT_THORNS 6
#define ITEM_EQUIP_EFFECT_ENDURE_KO 7
#define ITEM_EQUIP_EFFECT_EJECT 8
#define ITEM_EQUIP_EFFECT_STATCHANGE 9
#define ITEM_EQUIP_EFFECT_LOCKEDIN_MOVE 10

#define INV_USABLE_ITEM_0 0
#define INV_USABLE_ITEM_1 1
#define INV_USABLE_ITEM_2 2
#define INV_USABLE_ITEM_3 3
#define INV_USABLE_ITEM_4 4
#define INV_USABLE_ITEM_5 5
#define INV_USABLE_ITEM_6 6
#define INV_USABLE_ITEM_7 7
#define INV_USABLE_ITEM_8 8
#define INV_USABLE_ITEM_9 9
#define INV_USABLE_ITEM_10 10
#define INV_USABLE_ITEM_11 11
#define INV_USABLE_ITEM_12 12
#define INV_USABLE_ITEM_13 13
#define INV_USABLE_ITEM_14 14
#define INV_USABLE_ITEM_15 15
#define INV_USABLE_ITEM_16 16
#define INV_USABLE_ITEM_17 17
#define INV_USABLE_ITEM_18 18
#define INV_USABLE_ITEM_19 19
#define INV_USABLE_ITEM_20 20
#define INV_USABLE_ITEM_21 21
#define INV_USABLE_ITEM_22 22
#define INV_USABLE_ITEM_23 23
#define INV_USABLE_ITEM_24 24
#define INV_USABLE_ITEM_25 25
#define INV_USABLE_ITEM_26 26

#define NUM_USABLE_ITEMS 27

#define ITEM_USE_EFFECT_NULL 0
#define ITEM_USE_EFFECT_HEAL_MONSTER 1
#define ITEM_USE_EFFECT_CAPTURE 2
#define ITEM_USE_EFFECT_EXP_MONSTER 3
#define ITEM_USE_EFFECT_HAPPINESS 4
#define ITEM_USE_EFFECT_TRAINING_INC 5
#define ITEM_USE_EFFECT_TRAINING_DEC 6
#define ITEM_USE_EFFECT_UPGRADE 7
#define ITEM_USE_EFFECT_TEACHMOVE_ONCE 8
#define ITEM_USE_EFFECT_TEACHMOVE_INFINITE 9
#define ITEM_USE_EFFECT_CURE_STATUS 10
#define ITEM_USE_EFFECT_NO_ENCOUNTER 11
#define ITEM_USE_EFFECT_INC_ENCOUNTER 12
#define ITEM_USE_EFFECT_REVIVE_MONSTER 13

#define INV_VALUABLE_ITEM_0 0
#define INV_VALUABLE_ITEM_1 1
#define INV_VALUABLE_ITEM_2 2
#define INV_VALUABLE_ITEM_3 3
#define INV_VALUABLE_ITEM_4 4
#define INV_VALUABLE_ITEM_5 5
#define INV_VALUABLE_ITEM_6 6
#define INV_VALUABLE_ITEM_7 7
#define INV_VALUABLE_ITEM_8 8
#define INV_VALUABLE_ITEM_9 9
#define INV_VALUABLE_ITEM_10 10
#define INV_VALUABLE_ITEM_11 11
#define INV_VALUABLE_ITEM_12 12
#define INV_VALUABLE_ITEM_13 13
#define INV_VALUABLE_ITEM_14 14
#define INV_VALUABLE_ITEM_15 15
#define INV_VALUABLE_ITEM_16 16
#define INV_VALUABLE_ITEM_17 17
#define INV_VALUABLE_ITEM_18 18
#define INV_VALUABLE_ITEM_19 19
#define INV_VALUABLE_ITEM_20 20
#define INV_VALUABLE_ITEM_21 21
#define INV_VALUABLE_ITEM_22 22
#define INV_VALUABLE_ITEM_23 23
#define INV_VALUABLE_ITEM_24 24

#define NUM_VALUABLE_ITEMS 25

#define INV_ADVENTURE_ITEM_0 0
#define INV_ADVENTURE_ITEM_1 1
#define INV_ADVENTURE_ITEM_2 2
#define INV_ADVENTURE_ITEM_3 3
#define INV_ADVENTURE_ITEM_4 4
#define INV_ADVENTURE_ITEM_5 5
#define INV_ADVENTURE_ITEM_6 6
#define INV_ADVENTURE_ITEM_7 7
#define INV_ADVENTURE_ITEM_8 8
#define INV_ADVENTURE_ITEM_9 9
#define INV_ADVENTURE_ITEM_10 10
#define INV_ADVENTURE_ITEM_11 11
#define INV_ADVENTURE_ITEM_12 12
#define INV_ADVENTURE_ITEM_13 13
#define INV_ADVENTURE_ITEM_14 14
#define INV_ADVENTURE_ITEM_15 15
#define INV_ADVENTURE_ITEM_16 16
#define INV_ADVENTURE_ITEM_17 17
#define INV_ADVENTURE_ITEM_18 18
#define INV_ADVENTURE_ITEM_19 19
#define INV_ADVENTURE_ITEM_20 20
#define INV_ADVENTURE_ITEM_21 21
#define INV_ADVENTURE_ITEM_22 22
#define INV_ADVENTURE_ITEM_23 23
#define INV_ADVENTURE_ITEM_24 24

#define NUM_ADVENTURE_ITEMS 25

//////////////////////////////ITEMS////////////////////////////////////

/////////////////////////////ELEMENTS//////////////////////////////////
#define ELEMENT_NONE 0		//calcite
#define ELEMENT_EARTH 1		//topaz		amber
#define ELEMENT_AIR 2		//gypsum	opal	turquoise
#define ELEMENT_FIRE 3		//cinnabar	ruby
#define ELEMENT_WATER 4		//saphire	opal	pearl
#define ELEMENT_ELECTRIC 5	//quartz	magnetite
#define ELEMENT_METAL 6		//titanite	hematite
#define ELEMENT_SOUL 7		//amethyst
#define ELEMENT_LIFE 8		//emerald	jadeite
#define ELEMENT_DEATH 9		//onyx		jet	coal

#define ELEMENT_COUNT 10

#define ELEMENT_NULL 255
#define ELEMENT_STATUS 254

//elemental relationships

#define ELEMENT_NEUTRAL 0
#define ELEMENT_RESIST 1
#define ELEMENT_BONUS 2
#define ELEMENT_IMMUNE 3

#define ELEMENT_4X_BONUS 4
#define ELEMENT_4X_RESIST 5

/////////////////////////////ELEMENTS//////////////////////////////////

/////////////////////////////MONSTERS//////////////////////////////////

#define MONSTER_NULL 0
#define MONSTER_WOLF 1
#define MONSTER_EARTHWOLF 2
#define MONSTER_AIRWOLF 3
#define MONSTER_FIREWOLF 4
#define MONSTER_WATERWOLF 5
#define MONSTER_ELECTRICWOLF 6
#define MONSTER_METALWOLF 7
#define MONSTER_SOULWOLF 8
#define MONSTER_LIFEWOLF 9
#define MONSTER_DEATHWOLF 10

#define NUM_MONSTERS (11)

/////////////////////////////MONSTERS//////////////////////////////////

///////////////////////////////MOVES///////////////////////////////////

#define BATTLEMOVE_NULL 0
#define BATTLEMOVE_POUNCE 1
#define BATTLEMOVE_GROWL 2
#define BATTLEMOVE_BARK 3
#define BATTLEMOVE_SCRATCH 4
#define BATTLEMOVE_BITE 5

#define BATTLEMOVE_GROUND_POUND 6
#define BATTLEMOVE_BREEZE_ATTACK 7
#define BATTLEMOVE_FIRE_CHARGE 8
#define BATTLEMOVE_SPLASH_ATTACK 9
#define BATTLEMOVE_SHOCK_SPRINT 10
#define BATTLEMOVE_IRON_SLAM 11
#define BATTLEMOVE_SPIRIT_SMACK 12
#define BATTLEMOVE_FLORAL_ATTACK 13
#define BATTLEMOVE_DEADLY_SWIPE 14

#define NUM_BATTLEMOVES 15

#define MONSTER_HAS_MAX_MOVES 0xFFFF
#define MONSTER_ALREADY_KNOWS_MOVE 0xFFFE
#define MONSTER_MOVE_NONE 0

#define EFFECT_HIT 0
#define EFFECT_MULTI_HIT 1
#define EFFECT_HIT_FLINCH 2
#define EFFECT_ATTACK_UP 3
#define EFFECT_ATTACK_DOWN 4
#define EFFECT_DEFENSE_UP 5
#define EFFECT_DEFENSE_DOWN 6

#define FLAG_CONTACTMOVE 1
#define FLAG_BLOCKABLEMOVE 2
#define FLAG_STATUSMOVE 3

#define SPLIT_PHYS 0x0
#define SPLIT_PSI 0x1
#define SPLIT_STATUS 0x2

#define MOVE_TARGET_OPPONENT 0
#define MOVE_TARGET_SELF 1

///////////////////////////////MOVES///////////////////////////////////

////////////////////////SIGNATURE//MOVES///////////////////////////////

#define BATTLESIGMOVE_NULL 0
#define BATTLESIGMOVE_AGGRESIVE_ATTACK 1
#define BATTLESIGMOVE_AGGRESIVE_ELEMENT 2

#define NUM_BATTLESIGMOVES (3 - 1)

////////////////////////SIGNATURE//MOVES///////////////////////////////

///////////////////////////ABILITIES///////////////////////////////////

#define NORMAL_ABILITY_SLOTS 2
#define HIDDEN_ABILITY_SLOTS 1

#define ABILITY_NAME_LENGTH 16
#define NUM_ABILITY_SLOTS (NORMAL_ABILITY_SLOTS + HIDDEN_ABILITY_SLOTS)

///////

#define ABILITY_NONE 0
#define ABILITY_RUFF_HOUSE 1
#define ABILITY_KEEN_EYE 2
#define ABILITY_WATCHFUL 3

#define NUM_ABILITIES (4 - 1)

///////////////////////////ABILITIES///////////////////////////////////


