#pragma once

#define TILE_GRASS_01 1

#define TILE_WATER_01 2

#define TILE_NULL 3

#define TILE_STONEBRICKS_FLOOR_01 4

#define TILE_TELEPORT01 5

#define TILE_STONEBRICKS_WALL01 6

#define TILE_STONEBRICKS_WALL02 7

#define TILE_TALLGRASS_01 8

#define TILE_ROCK_01 9