#pragma once

#define TILE_GRASS_01 1

#define TILE_WATER_01 2

#define TILE_NULL 3

#define TILE_STONEBRICKS_FLOOR_01 4

#define TILE_TELEPORT01 5

#define TILE_STONEBRICKS_WALL01 6

#define TILE_STONEBRICKS_WALL02 7

#define TILE_TALLGRASS_01 8

#define TILE_ROCK_01 9

#define TILE_VOID 10

#define TILE_WOODFLOOR_01 11

#define TILE_WOODFLOOR_03 12

#define TILE_WOODFLOOR_02 13

#define TILE_HOUSEWALL_01 14

#define TILE_HOUSEWALL_02 15

#define TILE_WOODFLOOR_05 16

#define TILE_WOODFLOOR_04 17

#define TILE_WOODFLOOR_06 18

#define NUM_TILES 19

#define NUM_PASSABLE_TILES 8

#define NUM_ENCOUNTER_TILES 2

#define UNIQUE_TELEPADS_COUNT 4